"""migration from sqlite

Revision ID: 56f1be2cd3c
Revises: 261997119e
Create Date: 2017-01-22 14:27:46.568469

"""

# revision identifiers, used by Alembic.
revision = '56f1be2cd3c'
down_revision = '261997119e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
